### ISSUE TITLE
no support for Insert key on Linux?

### ISSUE THREAD

**Issue by idun-project** [Kerndog73/The-Fat-Controller#10] opened 2024-01-11 12:47 UTC
Howdy. I don't see any "Key::Insert" enum entry or use of "KEY_INSERT". Is there a reason it is not supported?

**Comment by indianakernick** [comment] 2024-01-15 00:48
There's no particular reason for it not being supported. I guess it seemed a bit obscure at the time. While I'm at it, are there any other missing keys?

**Comment by BrianHoldsworth** [comment] 2024-01-15 02:08
Ok, good to know. Some other "common" keys that might be useful to someone and don't seem to be included are: KEY_NUMLOCK, KEY_SCROLLLOCK, KEY_SYSRQ, KEY_MENU

**Comment by indianakernick** [comment] 2024-01-15 04:40
Ah, I think I know why it wasn't included. There isn't an insert key on macOS. So if `Key::Insert` was added, we have that edge-case to deal with on macOS.

I think the `Key` enum should be as platform-independent as possible. When it comes to keys that are not supported by some operating systems, it seems to me that it might be better to have a function that takes a platform-specific key code. That seems like a pain to use though. Especially since Windows and Linux both have an insert key but they obviously won't use the same key code.

Maybe having `Key::Insert` simply do nothing on macOS is the way to go. I might need to give this some thought.

**Comment by indianakernick** [comment] 2024-01-16 22:27
I added `Key::Insert` shortly after I wrote my previous comment. I didn't add the others because they're not supported by all platforms. I'll add them if someone says that they need them but to me they seem too obscure to be added just-in-case.

I saw your comment on the other issue. Can you confirm that this solves your problem so that I can publish a new release?

**Comment by BrianHoldsworth** [comment] 2024-01-16 23:31
Yes, I confirmed your changes and all good to go for me. Thanks again!

**Comment by indianakernick** [comment] 2024-01-16 23:56
Closing as resolved since version 0.7.0 has been published.

**Closed as completed by indianakernick** 2024-01-16 23:56 UTC
