### ISSUE TITLE
unicode_string collapses repeated characters

### ISSUE THREAD

**Issue by branpk** [Kerndog73/The-Fat-Controller#2] opened 2021-02-27 03:10 UTC
Using 0.5.1 on Windows 10, the following code types `abc`:

```rust
use tfc::{traits::*, Context, Error};

fn main() -> Result<(), Error> {
    let mut ctx = Context::new()?;
    ctx.unicode_string("aabcccc")?;
    Ok(())
}
```

`ascii_string` works as expected.

**Comment by indianakernick** [comment] 2021-02-27 03:26
I’m not able to reproduce this problem in a Windows 10 VM. Perhaps the application that’s receiving input is doing the collapsing? I used Notepad to test this. Can you provide some more information?

---

Hold up! I was able to reproduce it in Command Prompt. This is quite odd. I’ll look into it.

**Comment by indianakernick** [comment] 2021-02-27 04:31
I've pushed a fix for this. Repeating characters are indeed repeating for me in Notepad and Command Prompt. Can you confirm that this is working on your end?

**Comment by branpk** [comment] 2021-02-27 13:56
Yep the fix works for me. Thanks!

**Closed as completed** 2021-02-27 20:49 UTC
